###############################################################################
# Copyright (c) 2010, SugarCRM, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of SugarCRM, Inc. nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL SugarCRM, Inc. BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
###############################################################################

$sodalookups= {  
  'area' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'button' => {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => true,
    'for' => false,
  },  
  'cell' => {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
    },  'checkbox' =>
    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'div' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'file_field' =>    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => false,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => true,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'form' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => false,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => true,
    'action' => true,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'frame' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => false,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => true,
    'for' => false,
  },
  'hidden' =>    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => true,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'image' =>    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'alt' => true,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => true,
    'for' => false,
  },
  'label' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => true,
  },
  'li' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'link' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => true,
    'src' => false,
    'for' => false,
  },
  'map' =>    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'p' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'pre' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'radio' =>    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'row' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'select_list' =>    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'span' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'table' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'text_field' =>    {
    'id' => true,
    'name' => true,
    'value' => true,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'ul' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'h1' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'h2' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'h3' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'h4' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'h5' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
  'h6' =>    {
    'id' => true,
    'name' => true,
    'value' => false,
    'text' => true,
    'index' => true,
    'class' => true,
    'xpath' => true,
    'title' => false,
    'method' => false,
    'action' => false,
    'href' => false,
    'src' => false,
    'for' => false,
  },
};
